import { ReactNode } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import CssBaseline from "@mui/material/CssBaseline"
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <AppRouterCacheProvider options={{key: 'css', enableCssLayer: true}}>
          <ThemeProvider theme={theme}>
            <CssBaseline/>
                {children}
          </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
);
}
